export const RouterUrl = {
    LANDINGPAGE:'/',
    SIGNUPPAGE:'/Signup',
    LOGIN:'/Login',
    ADMINSIDE:'/AdminDashboard/Home',
    ADMINBOOKING:'/AdminDashboard/Booking',
    ADMINACCOUNTS:'/AdminDashboard/Accounts',
    ADMINTRAVELTALK:'/AdminDashboard/AllPost',
    ADMINPROFILE:'/AdminDashboard/Profile',
    TRAVELLERSIDE:'/UserDashBoard/HomePage',
    TRAVELLERBOOKING:'/UserDashBoard/MakeABooking',
    TRAVELLERPLAN:'/UserDashBoard/PlanYourTrip',
    TRAVELLERTALK:'/UserDashBoard/ViewAndShareTalks',
    TRAVELLERADVENTURE:'/UserDashBoard/Adventures',
    TRAVELLERMAPS:'/UserDashBoard/Map',
    TRAVELLERPROFILE:'/UserDashBoard/Profile',
    TOURISTSELECTED:'/UserDashBoard/HomePage/:type/:name',
    BUSINESSSIDE:'/BusinessDashBoard',
    BUSINESSBOOKING:'/BusinessDashBoard/Booking',
    BUSINESSMINE:'/BusinessDashBoard/MyBusiness',
    BUSINESSTALK:'/BusinessDashBoard/Talk',
    BUSINESSPROFILE:'/BusinessDashBoard/Profile',
    TOURISTSELECTEDBUSINESS:'/BusinessDashBoard/HomePage/:type/:name',
    // ERROR: '/*',
}